name: CI
on:
  push: { branches: [ main ] }
  pull_request: {}

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_API: ghcr.io/${{ github.repository }}/api
  IMAGE_WORKER: ghcr.io/${{ github.repository }}/worker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # API
      - uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: false
          tags: ${{ env.IMAGE_API }}:${{ github.sha }}
      - uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_API }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1
      - uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: |
            ${{ env.IMAGE_API }}:${{ github.sha }}
            ${{ env.IMAGE_API }}:main

      # Worker
      - uses: docker/build-push-action@v6
        with:
          context: ./apps/worker
          push: false
          tags: ${{ env.IMAGE_WORKER }}:${{ github.sha }}
      - uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_WORKER }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1
      - uses: docker/build-push-action@v6
        with:
          context: ./apps/worker
          push: true
          tags: |
            ${{ env.IMAGE_WORKER }}:${{ github.sha }}
            ${{ env.IMAGE_WORKER }}:main

